# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_s3_upload:

    docker:
      - image: circleci/python:3.7.4

    steps:
      - add_ssh_keys:
          fingerprints:
          - "SHA256:UPMMgFwPxY1QMBVUxMPAYxHQgj2tjbWurwiGIaBYF+I durgamuralidharan@Durgas-MacBook-Air.local"

      - checkout
      - run:
          name: Python dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip3 install --user -r requirements.txt
      
      - run:
          name: Run automated tests
          command: |
            python3 AppTest.py
        
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test_s3_upload:
    jobs:
      - build_s3_upload